// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using system_zawodnicy_zimowi.Data;

#nullable disable

namespace system_zawodnicy_zimowi.DATA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260119231904_Inicjalizacja")]
    partial class Inicjalizacja
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("system_zawodnicy_zimowi.core.Domain.Entities.KlubSportowy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dyscypliny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LimitMiejsc")
                        .HasColumnType("int");

                    b.Property<int?>("MaksWiek")
                        .HasColumnType("int");

                    b.Property<int>("MinimalnePunkty")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kluby");
                });

            modelBuilder.Entity("system_zawodnicy_zimowi.core.Domain.Entities.WynikZawodow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("Miejsce")
                        .HasColumnType("int");

                    b.Property<string>("NazwaZawodow")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PunktyBazowe")
                        .HasColumnType("int");

                    b.Property<int>("TrudnoscTrasy")
                        .HasColumnType("int");

                    b.Property<Guid?>("ZawodnikId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ZawodnikId");

                    b.ToTable("Wyniki");
                });

            modelBuilder.Entity("system_zawodnicy_zimowi.core.Domain.Entities.Zawodnik", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Dyscyplina")
                        .HasColumnType("int");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("KlubId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KlubNazwa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Punkty")
                        .HasColumnType("int");

                    b.Property<int>("Ranga")
                        .HasColumnType("int");

                    b.Property<string>("TypZawodnika")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<int>("Wiek")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Zawodnicy");

                    b.HasDiscriminator<string>("TypZawodnika").HasValue("Zawodnik");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("system_zawodnicy_zimowi.core.Domain.Entities.NarciarzAlpejski", b =>
                {
                    b.HasBaseType("system_zawodnicy_zimowi.core.Domain.Entities.Zawodnik");

                    b.HasDiscriminator().HasValue("Narciarz");
                });

            modelBuilder.Entity("system_zawodnicy_zimowi.core.Domain.Entities.Snowboardzista", b =>
                {
                    b.HasBaseType("system_zawodnicy_zimowi.core.Domain.Entities.Zawodnik");

                    b.HasDiscriminator().HasValue("Snowboardzista");
                });

            modelBuilder.Entity("system_zawodnicy_zimowi.core.Domain.Entities.WynikZawodow", b =>
                {
                    b.HasOne("system_zawodnicy_zimowi.core.Domain.Entities.Zawodnik", null)
                        .WithMany("Wyniki")
                        .HasForeignKey("ZawodnikId");
                });

            modelBuilder.Entity("system_zawodnicy_zimowi.core.Domain.Entities.Zawodnik", b =>
                {
                    b.Navigation("Wyniki");
                });
#pragma warning restore 612, 618
        }
    }
}
